In [1]:
from __future__ import print_function
import torch
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x =  torch.rand(5,3)
print(x)

tensor([[ 0.5179,  0.3022,  0.8384],
        [ 0.8703,  0.0929,  0.3813],
        [ 0.0551,  0.1531,  0.8949],
        [ 0.5342,  0.9241,  0.4972],
        [ 0.2732,  0.8925,  0.6214]])


In [3]:
z = torch.zeros(5,3, dtype=torch.long)
print(z)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [4]:
d = torch.tensor([[1,2,3], [4,5,6]])
print(d)

tensor([[ 1,  2,  3],
        [ 4,  5,  6]])


In [5]:
x = torch.ones(5,3, dtype=torch.double)
print(x)

x1 = torch.rand_like(x, dtype=torch.float)
print(x1)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.0811,  0.4588,  0.3900],
        [ 0.6597,  0.7343,  0.9619],
        [ 0.4103,  0.8274,  0.0575],
        [ 0.9582,  0.9144,  0.6768],
        [ 0.0172,  0.1047,  0.1419]])


In [6]:
print(x.size())

torch.Size([5, 3])


In [7]:
y  = torch.rand_like(x)
print(x + y)

tensor([[ 1.9519,  1.5379,  1.3630],
        [ 1.1379,  1.2422,  1.8587],
        [ 1.4083,  1.6140,  1.7061],
        [ 1.6237,  1.7795,  1.6019],
        [ 1.5455,  1.0876,  1.3717]], dtype=torch.float64)


In [8]:
resul = torch.empty(x.size(), dtype=torch.double)
print(x.type(), y.type())
torch.add(x, y, out=resul)
print(resul)

torch.DoubleTensor torch.DoubleTensor
tensor([[ 1.9519,  1.5379,  1.3630],
        [ 1.1379,  1.2422,  1.8587],
        [ 1.4083,  1.6140,  1.7061],
        [ 1.6237,  1.7795,  1.6019],
        [ 1.5455,  1.0876,  1.3717]], dtype=torch.float64)


In [9]:
print(x)
x.add_(y)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 1.9519,  1.5379,  1.3630],
        [ 1.1379,  1.2422,  1.8587],
        [ 1.4083,  1.6140,  1.7061],
        [ 1.6237,  1.7795,  1.6019],
        [ 1.5455,  1.0876,  1.3717]], dtype=torch.float64)


In [10]:
print(x[:1, :])

tensor([[ 1.9519,  1.5379,  1.3630]], dtype=torch.float64)


In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 4)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


In [12]:
a = np.ones((3,2))
print(a)
b = torch.from_numpy(a)
b.add_(1)
print(a)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]
tensor([[ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.]], dtype=torch.float64)


In [13]:
print(torch.cuda.is_available())

False


In [14]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [15]:
y = x +2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [16]:
print(y.grad_fn)

In [17]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [18]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [19]:
out.backward()

In [20]:
print(x)
print(x.grad)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [21]:
print(y.grad)

None


In [22]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [23]:
params = list(net.parameters())
print(len(params))
for param in params:
 print(param.size())

10
torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([16, 6, 5, 5])
torch.Size([16])
torch.Size([120, 400])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [24]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)
print(out.grad_fn)

tensor([[-0.1148, -0.0954,  0.0698, -0.0335, -0.1338,  0.1111,  0.0410,
         -0.0037, -0.0322,  0.0175]])


In [25]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [26]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.0289)


In [27]:
print (loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[0][0])

In [28]:
net.zero_grad()

print('net.conv1.bias.grad before')
print(net.conv1.bias.grad)
print(net.conv1.weight.grad)
print(net.conv1.weight.grad_fn)

loss.backward()

print('net.conv1.bias.grad after')
print(net.conv1.bias.grad)
print(net.conv1.weight.grad)
print(net.conv1.weight.grad_fn)

net.conv1.bias.grad before
tensor([ 0.,  0.,  0.,  0.,  0.,  0.])
tensor([[[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,